[2022-10-18 06:13:29,680] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-10-18T06:13:27.731070+00:00 [queued]>
[2022-10-18 06:13:29,699] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-10-18T06:13:27.731070+00:00 [queued]>
[2022-10-18 06:13:29,700] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 06:13:29,702] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-18 06:13:29,703] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 06:13:29,712] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-10-18 06:13:27.731070+00:00
[2022-10-18 06:13:29,719] {standard_task_runner.py:52} INFO - Started process 2186 to run task
[2022-10-18 06:13:29,722] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-10-18T06:13:27.731070+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpv7npe947', '--error-file', '/tmp/tmpk9yjs6bw']
[2022-10-18 06:13:29,724] {standard_task_runner.py:80} INFO - Job 63: Subtask is_api_available
[2022-10-18 06:13:29,802] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-10-18T06:13:27.731070+00:00 [running]> on host 5282528dd996
[2022-10-18 06:13:29,848] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-10-18T06:13:27.731070+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-18T06:13:27.731070+00:00
[2022-10-18 06:13:29,851] {http.py:97} INFO - Poking: api/
[2022-10-18 06:13:29,871] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-18 06:13:29,878] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-10-18 06:13:30,014] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-18 06:13:30,026] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20221018T061327, start_date=20221018T061329, end_date=20221018T061330
[2022-10-18 06:13:30,066] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-18 06:13:30,109] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
