[2022-10-18 05:54:50,100] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2022-10-18 05:54:50,119] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2022-10-18 05:54:50,121] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 05:54:50,122] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-18 05:54:50,123] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 05:54:50,144] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-10-17 00:00:00+00:00
[2022-10-18 05:54:50,150] {standard_task_runner.py:52} INFO - Started process 1279 to run task
[2022-10-18 05:54:50,160] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpwtiw_a7w', '--error-file', '/tmp/tmp3e871532']
[2022-10-18 05:54:50,164] {standard_task_runner.py:80} INFO - Job 58: Subtask create_table
[2022-10-18 05:54:50,294] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-10-17T00:00:00+00:00 [running]> on host 5282528dd996
[2022-10-18 05:54:50,415] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2022-10-18 05:54:50,430] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-18 05:54:50,442] {dbapi.py:208} INFO - Running statement: 
            create table if not exists users(
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-10-18 05:54:50,448] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-10-18 05:54:50,480] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221017T000000, start_date=20221018T055450, end_date=20221018T055450
[2022-10-18 05:54:50,551] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-18 05:54:50,602] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
