[2022-09-14 04:46:09,608] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-09-14T04:46:07.429430+00:00 [queued]>
[2022-09-14 04:46:09,674] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-09-14T04:46:07.429430+00:00 [queued]>
[2022-09-14 04:46:09,676] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 04:46:09,677] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-14 04:46:09,678] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 04:46:09,699] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-14 04:46:07.429430+00:00
[2022-09-14 04:46:09,708] {standard_task_runner.py:52} INFO - Started process 12852 to run task
[2022-09-14 04:46:09,729] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2022-09-14T04:46:07.429430+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp1d1tgjxa', '--error-file', '/tmp/tmpf353n2wz']
[2022-09-14 04:46:09,747] {standard_task_runner.py:80} INFO - Job 21: Subtask create_table
[2022-09-14 04:46:09,933] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2022-09-14T04:46:07.429430+00:00 [running]> on host 5282528dd996
[2022-09-14 04:46:10,133] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T04:46:07.429430+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T04:46:07.429430+00:00
[2022-09-14 04:46:10,158] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-09-14 04:46:10,171] {dbapi.py:208} INFO - Running statement: 
        create table if not exists users(
                firstname TEXT NOT NULL,
                astname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
                );
        , parameters: None
[2022-09-14 04:46:10,185] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-09-14 04:46:10,234] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220914T044607, start_date=20220914T044609, end_date=20220914T044610
[2022-09-14 04:46:10,279] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-14 04:46:10,339] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
